Bravnar/42_webserv

.gitignore, Makefile, main.cpp, src/main.cpp
Proposal for this file structure:
```
📁 ./
├─ 📜 Makefile  
├─ 📜 README.md  
├─ 📁 src  
│  ├─ 📁 classes │ 📜 *.cpp *.hpp  
│  ├─ 📁 utils   │ 📜 *.cpp *.hpp  
│  ├─ 📜 main.cpp  
├─ 📁 ressources  │ 📜 ressources...  
├─ 📁 docs │ 📜 docs...  
```
Move main.cpp to src/main.cpp.
Fix Makefile to ensure it uses object files instead of cpp files for compilation.
Adapt Makefile to comply with the new file structure.
=> Structuration

Makefile, config_files/local.conf, index.html, src/classes/ClientHandler.cpp, src/classes/ClientHandler.hpp, src/classes/HttpRequest.cpp, src/classes/HttpRequest.hpp, src/classes/ServerConfig.cpp, src/classes/ServerConfig.hpp, src/classes/ServerManager.cpp, src/classes/ServerManager.hpp, src/main.cpp, src/utils/Convert.cpp, src/utils/Convert.hpp, www/index.html
Merged ConfigManager branch to HttpServer branch.
Fixed a missing reference in ConfigManager.
=> Http server

Makefile, config_files/local.conf, src/classes/ClientHandler.cpp, src/classes/ClientHandler.hpp, src/classes/HttpRequest.cpp, src/classes/Runtime.cpp, src/classes/Runtime.hpp, src/classes/ServerManager.cpp, src/classes/ServerManager.hpp, src/main.cpp
This PR introduces the `Runtime` class, which is responsible for initializing `ServerManager` and running the server.
- **Created `Runtime` class**  
- Handles initialization of `ServerManager`.  
- Manages the server execution flow.  
- Improves modularity by encapsulating server management inside `Runtime`.  
- Makes the codebase cleaner and easier to maintain.  
- Addresses issue #6 by ensuring proper server initialization.  
- Built and ran the server successfully.  
- Verified that `Runtime` correctly initializes and runs `ServerManager`.  
- Implementing routing.
=> Fix multi-instance not working

Dockerfile, Makefile, config_files/nginx.conf, docker-compose.yml
Run docker:
```bash
make up
```
Will up nginx and webserv with similar configurations
Stop it:
```bash
make down
```
=> Adding docker support to Webserv

src/classes/ClientHandler.cpp, src/classes/ClientHandler.hpp, src/classes/HttpRequest.cpp, src/classes/HttpRequest.hpp, src/classes/HttpResponse.cpp, src/classes/HttpResponse.hpp, src/classes/Runtime.cpp, src/classes/Runtime.hpp, src/classes/ServerManager.cpp
- Refored runtime logging
- Implemented exception handling instead of if-else statements
- Added support for .ico files
- Included debug print statements
- Refactored ClientHandler to use ifstream instead of io
=> Update Http server

Dockerfile, src/classes/ClientHandler.cpp, src/classes/ClientHandler.hpp, src/classes/HttpRequest.cpp, src/classes/HttpRequest.hpp, src/classes/HttpResponse.cpp, src/classes/HttpResponse.hpp, src/classes/Runtime.cpp, src/classes/Runtime.hpp, src/classes/ServerManager.cpp, src/classes/ServerManager.hpp, src/main.cpp, src/utils/Convert.cpp, src/utils/Convert.hpp
- **Improved**: Runtime logging for better debugging and monitoring.
- **Improved**: Code quality with cleaner and more maintainable code.
- **Optimized**: `vector<pollfd>` is now reserved for better memory management.
- **Autonomy**: `ClientHandler` is now more autonomous, improving its self-management capabilities.
- **Efficient File Handling**: Instead of loading files into RAM, they are now sent in live chunks.
- This refactoring fixes a bug where the server would crash due to lack of memory when attempting to load a large file.
=> Enhancements to Runtime Logging, Code Quality, and Efficient File Handling

.gitignore, src/classes/ClientHandler.cpp, src/classes/ClientHandler.hpp, src/classes/HttpInclude.hpp, src/classes/HttpRequest.cpp, src/classes/HttpRequest.hpp, src/classes/HttpResponse.cpp, src/classes/HttpResponse.hpp, src/classes/Runtime.cpp, src/classes/Runtime.hpp, src/classes/ServerManager.cpp, src/classes/ServerManager.hpp
**Summary**:
This pull request involves a necessary refactor of the web server code to improve readability and manageability. The previous codebase was difficult to maintain due to its complexity. This refactor enhances code clarity and includes some performance optimizations.
**Key Changes**:
- **Refactor**:
- Simplified complex logic to improve readability.
- Improved code structure for easier maintenance.
- **Optimizations**:
- Enhanced performance through critical code optimizations.
- Reduced memory usage and improved execution speed.
- Easier code navigation and modification.
- Improved overall performance and server responsiveness.
=> Http server code refactor

src/classes/HttpRequest.cpp, src/classes/HttpResponse.cpp
- HttpResponse now checking the file extension at the end, instead of checking it anywhere
- HttpRequest parser now removing ?queries from url -> may be needed later tho, specially for CGI
=> Minor fixes

Makefile, src/classes/ClientHandler.cpp, src/classes/ClientHandler.hpp, src/classes/ListingBuilder.cpp, src/classes/ListingBuilder.hpp
- Now sending directory listing
- Fix some minor bugs
=> Directory listing

src/classes/ClientHandler.cpp
- Remove debug output statements from buildResponse
=> Remove debug output statements from buildResponse

src/classes/ClientHandler.cpp
- Fixed the error 500 when requesting directory listing from a cgi location, the bug was introduced by myself (sorry :c)
=> fix error 500 on cgi

config_files/default.conf, src/classes/CgiHandler.cpp, src/classes/ClientHandler.cpp, src/utils/ParseUtils.cpp, www/cgi-php/index.php, www/cgi-php/upload.php, www/cgi-python/index.py, www/cgi-python/upload.py
- Implemented .php and .py CGI upload scripts
- Added a condition to ClientHandler to allow cgi uploads
- Added upload file boxes to CGI-Python and CGI-PHP pages
- Added unique file name handling
- Added security for failed uploads in both python and php
=> CGI Post .py and .php

www/cgi-bash/index.sh, www/cgi-php/index.php, www/cgi-php/upload.php, www/cgi-python/index.py, www/cgi-python/upload.py
Update cgi scripts to load the correct icon
=> fix icon ref

src/classes/CgiHandler.cpp, src/classes/ClientHandler.cpp
fixed weird segfault (thanks Ruiman)
added security for an .at() call
=> checking .at() and fixed segfault line

src/classes/CgiHandler.cpp, src/main.cpp
main cleanup
CGIhandler cleanup
fixes #63
=> closed STDERR in child, cleaned up main

src/classes/ErrorBuilder.cpp, www/error_template/index.html, www/siege/index.html
- Bug fix pages not redirecting correctly to ddance
=> Fix link paths for Dance Party in error templates

src/classes/CgiHandler.cpp, src/classes/ClientHandler.cpp, src/classes/Runtime.cpp, src/classes/Runtime.hpp, www/cgi-python/upload.py
Possible integration of correct SIGINT handling
I had to change the errno == EINTR in runtime to break !
Needs to be tested
potentially fixed #59
=> working ctrl C ?

src/classes/ClientHandler.cpp
- Bug fix where any telnet attempt would result on an http error
=> Fix telnet

src/classes/ClientHandler.cpp
=> Revert "Fix telnet"

.gitignore, Dockerfile, Makefile, config_files/virtual_hosts.conf, src/classes/ClientHandler.cpp, src/classes/ClientHandler.hpp, src/classes/Runtime.cpp, src/classes/Runtime.hpp, src/classes/ServerManager.cpp, src/classes/ServerManager.hpp
- Fix #76 
- Fix #81 
- Feature : WebservSIR can now handle Virtual hosts
You can test it by having multiple servers under the same host:port but having different server names
=> Virtual Hosting

www/cgi-php/calculator.html, www/cgi-php/calculator.php, www/cgi-php/index.php, www/cgi-php/style.css, www/cgi-python/calculator.html, www/cgi-python/calculator.py, www/ngneeeuh/index.html
enhance websites
maybe you can try the same for python @Bravnar
=> Refactor cgi-php index.php and ngneeeuh

Makefile, src/classes/ClientHandler.cpp, src/classes/ClientHandler.hpp, src/utils/ReplaceAll.cpp, src/utils/ReplaceAll.hpp
- Fix url inrequests not being parsed (replacing %20 by SPACE)
=> feat: add ReplaceAll utility for string manipulation
